(DEFINE-CONFIGURATION BUFFER
  ((DEFAULT-MODES (APPEND '(NYXT::VI-NORMAL-MODE) %SLOT-DEFAULT%))))
(DEFINE-CONFIGURATION PROMPT-BUFFER
  ((DEFAULT-MODES (APPEND '(NYXT::VI-INSERT-MODE) %SLOT-DEFAULT%))))
(DEFINE-CONFIGURATION BUFFER
  ((CURRENT-ZOOM-RATIO 2.0)))
(DEFINE-CONFIGURATION BUFFER
  ((DEFAULT-MODES (APPEND '(NYXT::VI-NORMAL-MODE) %SLOT-DEFAULT%))))
(DEFINE-CONFIGURATION PROMPT-BUFFER
  ((DEFAULT-MODES (APPEND '(NYXT::VI-INSERT-MODE) %SLOT-DEFAULT%))))
(DEFINE-CONFIGURATION BUFFER
  ((DEFAULT-MODES (APPEND '(NYXT::VI-NORMAL-MODE) %SLOT-DEFAULT%))))
(DEFINE-CONFIGURATION PROMPT-BUFFER
  ((DEFAULT-MODES (APPEND '(NYXT::VI-INSERT-MODE) %SLOT-DEFAULT%))))
(DEFINE-CONFIGURATION BUFFER
  ((DEFAULT-MODES %SLOT-DEFAULT%)))
(DEFINE-CONFIGURATION BUFFER
  ((DEFAULT-MODES %SLOT-DEFAULT%)))
(DEFINE-CONFIGURATION BUFFER
  ((DEFAULT-MODES (APPEND '(NYXT::VI-NORMAL-MODE) %SLOT-DEFAULT%))))
(DEFINE-CONFIGURATION PROMPT-BUFFER
  ((DEFAULT-MODES (APPEND '(NYXT::VI-INSERT-MODE) %SLOT-DEFAULT%))))
(DEFINE-CONFIGURATION BUFFER
  ((DEFAULT-MODES (APPEND '(NYXT::VI-NORMAL-MODE) %SLOT-DEFAULT%))))
(DEFINE-CONFIGURATION PROMPT-BUFFER
  ((DEFAULT-MODES (APPEND '(NYXT::VI-INSERT-MODE) %SLOT-DEFAULT%))))
(DEFINE-CONFIGURATION BUFFER
  ((DEFAULT-MODES (APPEND '(NYXT::VI-NORMAL-MODE) %SLOT-DEFAULT%))))
(DEFINE-CONFIGURATION PROMPT-BUFFER
  ((DEFAULT-MODES (APPEND '(NYXT::VI-INSERT-MODE) %SLOT-DEFAULT%))))
(DEFINE-CONFIGURATION BUFFER
  ((DEFAULT-MODES (APPEND '(NYXT::VI-NORMAL-MODE) %SLOT-DEFAULT%))))
(DEFINE-CONFIGURATION PROMPT-BUFFER
  ((DEFAULT-MODES (APPEND '(NYXT::VI-INSERT-MODE) %SLOT-DEFAULT%))))
(DEFINE-CONFIGURATION BUFFER
  ((DEFAULT-MODES (APPEND '(NYXT::VI-NORMAL-MODE) %SLOT-DEFAULT%))))
(DEFINE-CONFIGURATION PROMPT-BUFFER
  ((DEFAULT-MODES (APPEND '(NYXT::VI-INSERT-MODE) %SLOT-DEFAULT%))))
(DEFINE-CONFIGURATION BUFFER
  ((CURRENT-ZOOM-RATIO 1.0)))
(DEFINE-CONFIGURATION USER-BROWSER
  ((EXTERNAL-EDITOR-PROGRAM "emacsclient")))
(DEFINE-CONFIGURATION USER-BROWSER
  ((EXTERNAL-EDITOR-PROGRAM "emacsclient")))
(DEFINE-CONFIGURATION USER-BROWSER
  ((EXTERNAL-EDITOR-PROGRAM "emacsclient")))
